/*******************************************************************
* File Name : FCSetupControllerTest
* Description : Test class for FCSetupController.
* Copyright : CloudSPM
********************************************************************/

@isTest
private class FCSetupControllerTest {

    static testMethod void myUnitTest() {
    	FCSetupController controller = new FCSetupController();
    }
}