/*******************************************************************
* File Name : StockQuoteServiceTest
* Description : Test class for StockQuoteService.
* Copyright : CloudSPM
********************************************************************/

@isTest
private class StockQuoteServiceTest {

    static testMethod void myUnitTest() {
        StockQuoteService controller = new StockQuoteService();
    }
}