/*    
        Name            :      TestxmlnsOracleComAdfSvcErrors
        Author          :
        Date            :      17th Dec.,2013
        Decription      :      Test Class for xmlnsOracleComAdfSvcErrors Controller
*/
@isTest
public class TestxmlnsOracleComAdfSvcErrors{

    @isTest
    private static void test(){
        xmlnsOracleComAdfSvcErrors testObj = new xmlnsOracleComAdfSvcErrors();
        xmlnsOracleComAdfSvcErrors.ServiceErrorMessage obj1 = new xmlnsOracleComAdfSvcErrors.ServiceErrorMessage();
        xmlnsOracleComAdfSvcErrors.ServiceMessage obj2 = new xmlnsOracleComAdfSvcErrors.ServiceMessage();
        xmlnsOracleComAdfSvcErrors.ServiceDMLErrorMessage obj3 = new xmlnsOracleComAdfSvcErrors.ServiceDMLErrorMessage();
        xmlnsOracleComAdfSvcErrors.ServiceRowValErrorMessage obj4 = new xmlnsOracleComAdfSvcErrors.ServiceRowValErrorMessage();
        xmlnsOracleComAdfSvcErrors.ServiceAttrValErrorMessage obj5 = new xmlnsOracleComAdfSvcErrors.ServiceAttrValErrorMessage();
        
    }
}