/*    
        Name            :      TestxmlnsOracleComAdfSvcTypes 
        Author          :
        Date            :      17th Dec.,2013
        Decription      :      Test Class for xmlnsOracleComAdfSvcTypes  Controller
*/
@isTest
public class TestxmlnsOracleComAdfSvcTypes{

    @isTest
    private static void test(){
        xmlnsOracleComAdfSvcTypes testObj = new xmlnsOracleComAdfSvcTypes();
        xmlnsOracleComAdfSvcTypes.ChildFindCriteria obj = new xmlnsOracleComAdfSvcTypes.ChildFindCriteria(); 
        xmlnsOracleComAdfSvcTypes.BigDecimalResult obj1 = new xmlnsOracleComAdfSvcTypes.BigDecimalResult();
        xmlnsOracleComAdfSvcTypes.SortOrder obj2 = new xmlnsOracleComAdfSvcTypes.SortOrder();
        xmlnsOracleComAdfSvcTypes.FindCriteria obj3 = new xmlnsOracleComAdfSvcTypes.FindCriteria();
        xmlnsOracleComAdfSvcTypes.SortAttribute obj4 = new xmlnsOracleComAdfSvcTypes.SortAttribute();
        xmlnsOracleComAdfSvcTypes.AmountType obj5 = new xmlnsOracleComAdfSvcTypes.AmountType();
        
        xmlnsOracleComAdfSvcTypes.ProcessData  obj6 = new xmlnsOracleComAdfSvcTypes.ProcessData();
        xmlnsOracleComAdfSvcTypes.BooleanResult obj7 = new xmlnsOracleComAdfSvcTypes.BooleanResult();
        xmlnsOracleComAdfSvcTypes.DataObjectResult obj8 = new xmlnsOracleComAdfSvcTypes.DataObjectResult();
        xmlnsOracleComAdfSvcTypes.MeasureType obj9 = new xmlnsOracleComAdfSvcTypes.MeasureType();
        xmlnsOracleComAdfSvcTypes.MethodResult obj10 = new xmlnsOracleComAdfSvcTypes.MethodResult();
        xmlnsOracleComAdfSvcTypes.TimeResult obj11 = new xmlnsOracleComAdfSvcTypes.TimeResult();
        xmlnsOracleComAdfSvcTypes.ViewCriteriaRow obj12 = new xmlnsOracleComAdfSvcTypes.ViewCriteriaRow();
        xmlnsOracleComAdfSvcTypes.DateResult obj13 = new xmlnsOracleComAdfSvcTypes.DateResult();
        xmlnsOracleComAdfSvcTypes.BytesResult obj14 = new xmlnsOracleComAdfSvcTypes.BytesResult();
        xmlnsOracleComAdfSvcTypes.CtrlHint obj15 = new xmlnsOracleComAdfSvcTypes.CtrlHint();
        xmlnsOracleComAdfSvcTypes.DoubleResult obj16 = new xmlnsOracleComAdfSvcTypes.DoubleResult();
        xmlnsOracleComAdfSvcTypes.ViewCriteriaItem obj17 = new xmlnsOracleComAdfSvcTypes.ViewCriteriaItem();
        xmlnsOracleComAdfSvcTypes.ShortResult obj18 = new xmlnsOracleComAdfSvcTypes.ShortResult();
        xmlnsOracleComAdfSvcTypes.ProcessControl obj19 = new xmlnsOracleComAdfSvcTypes.ProcessControl();
        xmlnsOracleComAdfSvcTypes.BigIntegerResult obj20 = new xmlnsOracleComAdfSvcTypes.BigIntegerResult();
        xmlnsOracleComAdfSvcTypes.DataHandlerResult obj21 = new xmlnsOracleComAdfSvcTypes.DataHandlerResult();
        xmlnsOracleComAdfSvcTypes.FloatResult obj22 = new xmlnsOracleComAdfSvcTypes.FloatResult();
        xmlnsOracleComAdfSvcTypes.IntegerResult obj23 = new xmlnsOracleComAdfSvcTypes.IntegerResult();
        xmlnsOracleComAdfSvcTypes.StringResult obj24 = new xmlnsOracleComAdfSvcTypes.StringResult();
        xmlnsOracleComAdfSvcTypes.ByteResult obj25 = new xmlnsOracleComAdfSvcTypes.ByteResult();
        xmlnsOracleComAdfSvcTypes.LongResult obj26 = new xmlnsOracleComAdfSvcTypes.LongResult ();
        xmlnsOracleComAdfSvcTypes.FindControl obj27 = new xmlnsOracleComAdfSvcTypes.FindControl();
        xmlnsOracleComAdfSvcTypes.AttrCtrlHints obj28 = new xmlnsOracleComAdfSvcTypes.AttrCtrlHints();
        xmlnsOracleComAdfSvcTypes.ViewCriteria obj29 = new xmlnsOracleComAdfSvcTypes.ViewCriteria();
        xmlnsOracleComAdfSvcTypes.TimestampResult obj30 = new xmlnsOracleComAdfSvcTypes.TimestampResult();        
    }
}