@isTest
public class TestclassforOrecaleWebsvc{
    @isTest
    public static void testDemo(){
        commonjSdoXml.XMLInfo model = new commonjSdoXml.XMLInfo();
        commonjSdoJava.JavaInfo m2 = new commonjSdoJava.JavaInfo();
        commonjSdo.Type_x m3 = new commonjSdo.Type_x();
        commonjSdo.Types m4 = new commonjSdo.Types();
        commonjSdo.ModelsType  m5 = new commonjSdo.ModelsType();
        commonjSdo.TextType  m6 = new commonjSdo.TextType();
        commonjSdo.DataObject  m7 = new commonjSdo.DataObject();
        commonjSdo.XSDType  m8 = new commonjSdo.XSDType();
        commonjSdo.DataGraphType  m9 = new commonjSdo.DataGraphType ();
        commonjSdo.ChangeSummaryType  m10 = new commonjSdo.ChangeSummaryType();
        commonjSdo.BaseDataGraphType m11 = new commonjSdo.BaseDataGraphType();
        commonjSdo.Property m12 = new commonjSdo.Property();
        
        xmlnsOracleComOracleasSchemaOracle.detail  m13 = new xmlnsOracleComOracleasSchemaOracle.detail();
        xmlnsOracleComOracleasSchemaOracle.FaultType  m14 = new xmlnsOracleComOracleasSchemaOracle.FaultType();
                
    }
}