/*    
        Name            :      TestxmlnsOracleComAppsIncentivecompensat  
        Author          :
        Date            :      17th Dec.,2013
        Decription      :      Test Class for xmlnsOracleComAppsIncentivecompensat Controller
*/
@isTest
public class TestxmlnsOracleComAppsIncentivecompensat{

    @isTest
    private static void test(){
        xmlnsOracleComAppsIncentivecompensat  testObj = new xmlnsOracleComAppsIncentivecompensat();
        xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingAsyncResponse_element obj = new xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingAsyncResponse_element(); 
        xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingAsync_element obj1 = new xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingAsyncResponse_element obj2 = new xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingResponse_element obj3 = new xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.holdTransactionAsync_element obj4 = new xmlnsOracleComAppsIncentivecompensat.holdTransactionAsync_element();
        xmlnsOracleComAppsIncentivecompensat.Transaction_x obj5 = new xmlnsOracleComAppsIncentivecompensat.Transaction_x();
        
        xmlnsOracleComAppsIncentivecompensat.holdTransaction_element obj6 = new xmlnsOracleComAppsIncentivecompensat.holdTransaction_element();
        xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingAsync_element obj7 = new xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStaging_element obj8 = new xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.holdTransactionAsyncResponse_element obj9 = new xmlnsOracleComAppsIncentivecompensat.holdTransactionAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStaging_element obj10 = new xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingAsync_element obj11 = new xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingAsync_element  obj12 = new xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingAsyncResponse_element obj13 = new xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingAsyncResponse_element  obj14 = new xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.TransactionStaging obj15 = new xmlnsOracleComAppsIncentivecompensat.TransactionStaging();
        xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStaging_element obj16 = new xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.holdTransactionResponse_element obj17 = new xmlnsOracleComAppsIncentivecompensat.holdTransactionResponse_element();
        xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingResponse_element obj18 = new xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStaging_element obj19 = new xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStaging_element obj20 = new xmlnsOracleComAppsIncentivecompensat.processIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingAsyncResponse_element obj21 = new xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingResponse_element obj22 = new xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingAsync_element obj23 = new xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingAsyncResponse_element obj24 = new xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingAsync_element obj25 = new xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStaging_element obj26 = new xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingResponse_element obj27 = new xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingAsync_element obj28 = new xmlnsOracleComAppsIncentivecompensat.updateIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingResponse_element  obj29 = new xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingResponse_element obj30 = new xmlnsOracleComAppsIncentivecompensat.mergeIncentiveTransactionStagingResponse_element();        
        
        xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingResponse_element obj31 = new xmlnsOracleComAppsIncentivecompensat.getIncentiveTransactionStagingResponse_element();        
        xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStaging_element obj32 = new xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStaging_element obj33 = new xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStaging_element();
        xmlnsOracleComAppsIncentivecompensat.TransactionServiceSoapHttpPort obj34 = new xmlnsOracleComAppsIncentivecompensat.TransactionServiceSoapHttpPort();

        
        
        xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingResponse_element obj35 = new xmlnsOracleComAppsIncentivecompensat.deleteIncentiveTransactionStagingResponse_element();
        xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingAsync_element obj36 = new xmlnsOracleComAppsIncentivecompensat.findIncentiveTransactionStagingAsync_element();
        xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingAsyncResponse_element obj37 = new xmlnsOracleComAppsIncentivecompensat.createIncentiveTransactionStagingAsyncResponse_element();
        xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingAsyncResponse_element obj38 = new xmlnsOracleComAppsIncentivecompensat.processCSIncentiveTransactionStagingAsyncResponse_element();
    }
}